version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front-sansan_trigger2022
    ports:
      - 3000:80
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-sansan_trigger2022
    env_file:
      - docker-compose.env
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db-sansan_trigger2022
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    restart: always
